/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mindcracker;

import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author student
 */
public class Graph extends javax.swing.JFrame {

    /**
     * Creates new form Graph
     */
    public Graph() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tf3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(102, 102, 102));
        panel.setOpaque(false);
        panel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 240, 630, 580));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel1.setText("Marks :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 120, 100));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel2.setText("Time Taken  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 190, 100));

        jLabel3.setFont(new java.awt.Font("Blackadder ITC", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Aptitude Test  stats!!!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 410, 80));

        tf2.setEditable(false);
        tf2.setOpaque(false);
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 250, 60));

        tf1.setEditable(false);
        tf1.setOpaque(false);
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 250, 50));

        jButton1.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jButton1.setText("Next");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 640, 130, 60));

        tf3.setEditable(false);
        tf3.setOpaque(false);
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, 250, 50));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel4.setText("Your Level :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 170, 40));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/rsz_ic.png"))); // NOI18N
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel61.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(74, 152, 139));
        jLabel61.setText("MindCracker");
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel7.setText("Graph");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 160, 180, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/11027692.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1950, 1080));

        pack();
    }// </editor-fold>                        
void mark(int x,String o,int f)
{
    int u=x*4;
    tf1.setText(""+u);
    tf2.setText(o);
    tf3.setText(""+f);
}
void mark1(int x,String o)
{
    int u=x*4;
    tf1.setText(""+u);
    tf2.setText(o);
    tf3.setVisible(false);   
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         Mains1 g= new Mains1();
         g.ip_();
    }                                        


    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
int x=Integer.parseInt(tf1.getText());
int y=Integer.parseInt(tf2.getText());
DefaultCategoryDataset dataset= new DefaultCategoryDataset();
dataset.setValue(x,"","Marks");
dataset.setValue(y,"","Time Taken");
JFreeChart chart=ChartFactory.createLineChart("Marks Compilation","","", dataset, PlotOrientation.VERTICAL, false, false, false);
CategoryPlot catPlot=chart.getCategoryPlot();
catPlot.setRangeGridlinePaint(Color.YELLOW);
ChartPanel chartPanel=new ChartPanel(chart);
panel.removeAll();
panel.add(chartPanel,BorderLayout.CENTER);
panel.validate();
    }                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration                   
}
