/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mindcracker;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author student
 */
public class ip extends javax.swing.JFrame {

    /** Creates new form AI */
     
     private Timer t;
    private Timer i;
    private Timer u;
    private Timer op;
    private Timer p;
    private Timer q;
     private Timer q1; private Timer q2;
      private Timer q3;
       private Timer q4;
        private Timer q5;
    
    private int count =0;
     private int count1 =0;
      private int count2 =0;
       private int count3 =0;
        private int count4 =0;
         private int count5 =0;
         private int count6 =0;
         private int count7 =0;
         private int count8 =0;
         private int count9 =0;
         
         public String x;
         public String Y;
         
    public ip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        main_2 = new javax.swing.JDialog();
        rd53 = new javax.swing.JRadioButton();
        rd54 = new javax.swing.JRadioButton();
        rd55 = new javax.swing.JRadioButton();
        rd56 = new javax.swing.JRadioButton();
        jLabel42 = new javax.swing.JLabel();
        bb5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta3 = new javax.swing.JTextArea();
        tf57 = new javax.swing.JTextField();
        p3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        rd80 = new javax.swing.JRadioButton();
        rd81 = new javax.swing.JRadioButton();
        rd82 = new javax.swing.JRadioButton();
        rd83 = new javax.swing.JRadioButton();
        rd84 = new javax.swing.JRadioButton();
        rd85 = new javax.swing.JRadioButton();
        rd86 = new javax.swing.JRadioButton();
        rd87 = new javax.swing.JRadioButton();
        rd88 = new javax.swing.JRadioButton();
        rd89 = new javax.swing.JRadioButton();
        jButton10 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tf88 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sub = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        lk5 = new javax.swing.JLabel();
        hk5 = new javax.swing.JLabel();
        tt5 = new javax.swing.JLabel();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        lb20 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pt1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pd1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rd7 = new javax.swing.JRadioButton();
        rd8 = new javax.swing.JRadioButton();
        rd9 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        tg5 = new javax.swing.JLabel();
        gh5 = new javax.swing.JLabel();
        dsub = new javax.swing.JLabel();
        yh5 = new javax.swing.JLabel();

        main_2.setMinimumSize(new java.awt.Dimension(1920, 1080));
        main_2.setUndecorated(true);
        main_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                main_FocusGained(evt);
            }
        });
        main_2.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                main_WindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                main_WindowOpened(evt);
            }
        });
        main_2.getContentPane().setLayout(null);

        buttonGroup7.add(rd53);
        rd53.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        rd53.setText("A");
        rd53.setOpaque(false);
        rd53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd45ActionPerformed(evt);
            }
        });
        main_2.getContentPane().add(rd53);
        rd53.setBounds(520, 470, 810, 50);

        buttonGroup7.add(rd54);
        rd54.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        rd54.setText("B");
        rd54.setOpaque(false);
        rd54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd46ActionPerformed(evt);
            }
        });
        main_2.getContentPane().add(rd54);
        rd54.setBounds(520, 520, 810, 50);

        buttonGroup7.add(rd55);
        rd55.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        rd55.setText("C");
        rd55.setOpaque(false);
        rd55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd47ActionPerformed(evt);
            }
        });
        main_2.getContentPane().add(rd55);
        rd55.setBounds(520, 560, 810, 50);

        buttonGroup7.add(rd56);
        rd56.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        rd56.setText("D");
        rd56.setOpaque(false);
        rd56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd48ActionPerformed(evt);
            }
        });
        main_2.getContentPane().add(rd56);
        rd56.setBounds(520, 600, 810, 50);

        jLabel42.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(73, 150, 124));
        jLabel42.setText("Practice Test");
        main_2.getContentPane().add(jLabel42);
        jLabel42.setBounds(640, 190, 270, 70);

        bb5.setBackground(new java.awt.Color(0, 204, 204));
        bb5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        bb5.setText("Next Q");
        bb5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bb3FocusGained(evt);
            }
        });
        bb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb3ActionPerformed(evt);
            }
        });
        main_2.getContentPane().add(bb5);
        bb5.setBounds(970, 710, 130, 50);

        ta3.setEditable(false);
        ta3.setColumns(20);
        ta3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        ta3.setLineWrap(true);
        ta3.setRows(5);
        ta3.setOpaque(false);
        jScrollPane3.setViewportView(ta3);

        main_2.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(560, 310, 970, 80);

        tf57.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        tf57.setText("Q.NO");
        main_2.getContentPane().add(tf57);
        tf57.setBounds(460, 310, 80, 40);

        p3.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 22)); // NOI18N
        jLabel15.setText("Question's");

        rd80.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rd80);
        rd80.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        rd80.setForeground(new java.awt.Color(0, 0, 102));
        rd80.setText("01");
        rd80.setEnabled(false);
        rd80.setOpaque(false);

        rd81.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rd81);
        rd81.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        rd81.setForeground(new java.awt.Color(0, 0, 102));
        rd81.setText("02");
        rd81.setEnabled(false);
        rd81.setOpaque(false);

        rd82.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rd82);
        rd82.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        rd82.setForeground(new java.awt.Color(0, 0, 102));
        rd82.setText("03");
        rd82.setEnabled(false);
        rd82.setOpaque(false);

        rd83.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rd83);
        rd83.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        rd83.setForeground(new java.awt.Color(0, 0, 102));
        rd83.setText("04");
        rd83.setEnabled(false);
        rd83.setOpaque(false);

        rd84.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rd84);
        rd84.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        rd84.setForeground(new java.awt.Color(0, 0, 102));
        rd84.setText("05");
        rd84.setEnabled(false);
        rd84.setOpaque(false);

        rd85.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rd85);
        rd85.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        rd85.setForeground(new java.awt.Color(0, 0, 102));
        rd85.setText("06");
        rd85.setEnabled(false);
        rd85.setOpaque(false);

        rd86.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rd86);
        rd86.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        rd86.setForeground(new java.awt.Color(0, 0, 102));
        rd86.setText("07");
        rd86.setEnabled(false);
        rd86.setOpaque(false);

        rd87.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rd87);
        rd87.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        rd87.setForeground(new java.awt.Color(0, 0, 102));
        rd87.setText("08");
        rd87.setEnabled(false);
        rd87.setOpaque(false);

        rd88.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rd88);
        rd88.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        rd88.setForeground(new java.awt.Color(0, 0, 102));
        rd88.setText("09");
        rd88.setEnabled(false);
        rd88.setOpaque(false);

        buttonGroup1.add(rd89);
        rd89.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        rd89.setText("10");
        rd89.setEnabled(false);
        rd89.setOpaque(false);

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd89)
                    .addComponent(rd81)
                    .addComponent(rd80)
                    .addComponent(rd85)
                    .addComponent(rd82)
                    .addComponent(rd86)
                    .addComponent(rd87)
                    .addComponent(rd88)
                    .addComponent(rd83)
                    .addComponent(rd84))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(rd80)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rd81)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rd82)
                .addGap(6, 6, 6)
                .addComponent(rd83)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rd84)
                .addGap(4, 4, 4)
                .addComponent(rd85)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd86)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rd87)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rd88)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd89)
                .addContainerGap())
        );

        main_2.getContentPane().add(p3);
        p3.setBounds(280, 240, 190, 510);

        jButton10.setBackground(new java.awt.Color(75, 144, 144));
        jButton10.setFont(new java.awt.Font("Algerian", 0, 20)); // NOI18N
        jButton10.setText("EXIT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        main_2.getContentPane().add(jButton10);
        jButton10.setBounds(1680, 50, 110, 40);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/rsz_ic.png"))); // NOI18N
        main_2.getContentPane().add(jLabel55);
        jLabel55.setBounds(40, 10, 110, 110);

        jLabel56.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(74, 152, 139));
        jLabel56.setText("MindCracker");
        main_2.getContentPane().add(jLabel56);
        jLabel56.setBounds(160, 30, 270, 70);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jButton2.setText("Next Sub");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        main_2.getContentPane().add(jButton2);
        jButton2.setBounds(1160, 710, 140, 50);

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        main_2.getContentPane().add(jButton3);
        jButton3.setBounds(1360, 710, 130, 50);

        tf88.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        tf88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf88ActionPerformed(evt);
            }
        });
        main_2.getContentPane().add(tf88);
        tf88.setBounds(1460, 60, 110, 30);

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(62, 166, 131));
        jLabel13.setText("Time Taken");
        main_2.getContentPane().add(jLabel13);
        jLabel13.setBounds(1300, 60, 160, 28);

        sub.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        sub.setForeground(new java.awt.Color(0, 153, 102));
        main_2.getContentPane().add(sub);
        sub.setBounds(390, 120, 200, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/mRK1qN.jpg"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        main_2.getContentPane().add(jLabel25);
        jLabel25.setBounds(0, 0, 1920, 1080);
        main_2.getContentPane().add(lb8);
        lb8.setBounds(330, 30, 120, 30);

        lk5.setText("jLabel4");
        main_2.getContentPane().add(lk5);
        lk5.setBounds(770, 370, 41, 16);

        hk5.setText("0");
        main_2.getContentPane().add(hk5);
        hk5.setBounds(1100, 130, 7, 16);
        main_2.getContentPane().add(tt5);
        tt5.setBounds(650, 370, 120, 70);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 133, 133));
        jLabel1.setText("Practice Test");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 320, 70));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/rsz_ic.png"))); // NOI18N
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel61.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(74, 152, 139));
        jLabel61.setText("MindCracker");
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        lb20.setForeground(new java.awt.Color(28, 123, 75));
        lb20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/220px-User_icon_2.svg.png"))); // NOI18N
        getContentPane().add(lb20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 280, 160));

        jButton20.setBackground(new java.awt.Color(0, 204, 204));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/logout.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 60, 40, 40));

        jLabel33.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 51, 51));
        jLabel33.setText("log out");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 70, -1, -1));

        jButton8.setBackground(new java.awt.Color(51, 204, 255));
        jButton8.setFont(new java.awt.Font("Algerian", 0, 20)); // NOI18N
        jButton8.setText("EXIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1740, 60, 130, 40));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel2.setText("No Of Question's  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 280, 40));

        pt1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        pt1.setText("30");
        getContentPane().add(pt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 150, 30));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel3.setText("Time (Max)        :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 260, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel4.setText("Mark(Max)         :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 270, 40));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel5.setText("30 Mins");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 380, 110, 30));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel6.setText("360");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, 100, 30));

        pd1.setOpaque(false);
        pd1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 51));
        jLabel7.setText("Choose Your Order of Attempting");
        pd1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 390, 30));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 51));
        jLabel10.setText("Choose Your Subject (10 Q Each)  :");
        pd1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        rd7.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        rd7.setForeground(new java.awt.Color(0, 102, 51));
        rd7.setText("Mathematics");
        rd7.setOpaque(false);
        rd7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd7ActionPerformed(evt);
            }
        });
        pd1.add(rd7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, 30));

        rd8.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        rd8.setForeground(new java.awt.Color(0, 102, 51));
        rd8.setText("Chemistry");
        rd8.setOpaque(false);
        rd8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd8ActionPerformed(evt);
            }
        });
        pd1.add(rd8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        rd9.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        rd9.setForeground(new java.awt.Color(0, 102, 51));
        rd9.setText("physics");
        rd9.setOpaque(false);
        rd9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd9ActionPerformed(evt);
            }
        });
        pd1.add(rd9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jButton1.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jButton1.setText("Proceed ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pd1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 180, 50));

        getContentPane().add(pd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 1130, 270));

        b1.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        b1.setText("Start Practice");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 330, 190, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/MQ2bhqD5.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        level.setText("jLabel14");
        getContentPane().add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 100, 60));
        getContentPane().add(tg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 100, 20));
        getContentPane().add(gh5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, -1));
        getContentPane().add(dsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 130, 50));
        getContentPane().add(yh5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 140, 90));

        pack();
    }// </editor-fold>                        

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
    }                                         

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
 Mains1 o= new Mains1();
        o.thanks();
star1 d= new star1();
d.setVisible(true);
this.dispose();
    }                                        
void name(String x){
    yh5.setText(x);
    tg5.setText(x);
}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  

     pd1.setVisible(false);
      try {
                    Class.forName("java.sql.DriverManager");
                    Connection con = (Connection)
                            DriverManager.getConnection("jdbc:mysql://localhost:3306/sireesh", "root","root");
                    Statement stmt = (Statement) con.createStatement();
                   
                     String npa=tg5.getText();
                    String query="Select level,user_name from iit;";
                    ResultSet rs=stmt.executeQuery(query);
                   while(rs.next()) {
                        String qno = rs.getString("level");
                        String h=rs.getString("user_name");
                        if(h.equals(npa)){
                            gh5.setText(qno);
                            stmt.close();
                            con.close();
                        }
                        
                    }


                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }
      
      
          
    }                                 

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       pd1.setVisible(true);
       b1.setEnabled(false);
    }                                  

    private void rd7ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        rd8.setSelected(false);
       rd9.setSelected(false);
       
       sub.setText("Mathematics");
       dsub.setText("math"+level.getText());
    }                                   

    private void rd8ActionPerformed(java.awt.event.ActionEvent evt) {                                    
          rd7.setSelected(false);
       rd9.setSelected(false);
       
       sub.setText("Chemistry");
       dsub.setText("chem"+level.getText());
    }                                   

    private void rd9ActionPerformed(java.awt.event.ActionEvent evt) {                                    
          rd8.setSelected(false);
       rd7.setSelected(false);
       
       
       sub.setText("Physics");
       dsub.setText("phy"+level.getText());
    }                                   
void tyr(String x){
 try {
                    Class.forName("java.sql.DriverManager");
                    Connection con = (Connection)
                            DriverManager.getConnection("jdbc:mysql://localhost:3306/levela", "root","root");
                    Statement stmt = (Statement) con.createStatement();
                    String query=x;
                    ResultSet rs=stmt.executeQuery(query);

                    int Found=0;
                    while(rs.next())

                    {
                        String qno = rs.getString("sno");
                        String question = rs.getString("question");
                        String moq1 = rs.getString("moq1");
                        String moq2 = rs.getString("moq2");
                        String moq3 = rs.getString("moq3");
                        String moq4 = rs.getString("moq4");
                        String corr = rs.getString("correct1");
                        tf57.setText(""+qno);
                        ta3.setText(""+question);
                        rd53.setText(""+moq1);
                        rd54.setText(""+moq2);
                        rd55.setText(""+moq3);
                        rd56.setText(""+moq4);
                        lk5.setText(""+corr);
                        Found++;

                    }
                     } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }}
void tyr1(String x){
 try {
                    Class.forName("java.sql.DriverManager");
                    Connection con = (Connection)
                            DriverManager.getConnection("jdbc:mysql://localhost:3306/levelb", "root","root");
                    Statement stmt = (Statement) con.createStatement();
                    String query=x;
                    ResultSet rs=stmt.executeQuery(query);

                    int Found=0;
                    while(rs.next())

                    {
                        String qno = rs.getString("sno");
                        String question = rs.getString("question");
                        String moq1 = rs.getString("moq1");
                        String moq2 = rs.getString("moq2");
                        String moq3 = rs.getString("moq3");
                        String moq4 = rs.getString("moq4");
                        String corr = rs.getString("correct1");
                        tf57.setText(""+qno);
                        ta3.setText(""+question);
                        rd53.setText(""+moq1);
                        rd54.setText(""+moq2);
                        rd55.setText(""+moq3);
                        rd56.setText(""+moq4);
                        lk5.setText(""+corr);
                        Found++;

                    }
                     } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }}
void tyr2(String x){
 try {
                    Class.forName("java.sql.DriverManager");
                    Connection con = (Connection)
                            DriverManager.getConnection("jdbc:mysql://localhost:3306/levelc", "root","root");
                    Statement stmt = (Statement) con.createStatement();
                    String query=x;
                    ResultSet rs=stmt.executeQuery(query);

                    int Found=0;
                    while(rs.next())

                    {
                        String qno = rs.getString("sno");
                        String question = rs.getString("question");
                        String moq1 = rs.getString("moq1");
                        String moq2 = rs.getString("moq2");
                        String moq3 = rs.getString("moq3");
                        String moq4 = rs.getString("moq4");
                        String corr = rs.getString("correct1");
                        tf57.setText(""+qno);
                        ta3.setText(""+question);
                        rd53.setText(""+moq1);
                        rd54.setText(""+moq2);
                        rd55.setText(""+moq3);
                        rd56.setText(""+moq4);
                        lk5.setText(""+corr);
                        Found++;

                    }
                     } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }}
void math(int c,String g)
{
    if(c==1){
        String query1 =null;
        int i=1;
        if(rd80.isSelected()) {
            rd81.setSelected(true);
            if(rd81.isSelected()) {
                ta3.setWrapStyleWord(true);
                ta3.setLineWrap(true);
                i=02;
                query1="SELECT *FROM "+g+" where sno='"+i+"';";

                tyr(query1);

            }} else if(rd81.isSelected()) {
                rd82.setSelected(true);
                if(rd82.isSelected()) {
ta3.setWrapStyleWord(true);
                        ta3.setLineWrap(true);
                    i=03;
                    query1="SELECT *FROM "+g+" where sno='"+i+"';";

                    tyr(query1);
                }} else if(rd82.isSelected()){
                    rd83.setSelected(true);
                    if(rd83.isSelected()) {
                        ta3.setWrapStyleWord(true);
                        ta3.setLineWrap(true);

                        i=04;
                        query1="SELECT *FROM "+g+" where sno='"+i+"';";

                        tyr(query1);
                    }} else if(rd83.isSelected()){
                        rd84.setSelected(true);
                        if(rd84.isSelected()) {
                            ta3.setWrapStyleWord(true);
                            ta3.setLineWrap(true);

                            i=05;
                            query1="SELECT *FROM "+g+" where sno='"+i+"';";

                            tyr(query1);
                        }} else if(rd84.isSelected()){
                            rd85.setSelected(true);
                            if(rd85.isSelected()) {
                                ta3.setWrapStyleWord(true);
                                ta3.setLineWrap(true);

                                i=06;
                                query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                tyr(query1);
                            }} else if(rd85.isSelected()){
                                rd86.setSelected(true);
                                if(rd86.isSelected()) {
                                    ta3.setWrapStyleWord(true);
                                    ta3.setLineWrap(true);

                                    i=07;
                                    query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                    tyr(query1);
                                }} else if(rd86.isSelected()){
                                    rd87.setSelected(true);
                                    if(rd87.isSelected()) {
                                        ta3.setWrapStyleWord(true);
                                        ta3.setLineWrap(true);

                                        i = 8;
                                        query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                        tyr(query1);
                                    }} else if(rd87.isSelected()){
                                        rd88.setSelected(true);
                                        if(rd88.isSelected()) {
                                            ta3.setWrapStyleWord(true);
                                            ta3.setLineWrap(true);

                                            i=9;
                                            query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                            tyr(query1);
                                        }}
        else if(rd88.isSelected()){
                                        rd89.setSelected(true);
                                        if(rd89.isSelected()) {
                                            ta3.setWrapStyleWord(true);
                                            ta3.setLineWrap(true);

                                            i=10;
                                            query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                            tyr(query1);
                                        }}}
else if(c==2){
    
        String query1 =null;
        int i=1;
        if(rd80.isSelected()) {
            rd81.setSelected(true);
            if(rd81.isSelected()) {
                ta3.setWrapStyleWord(true);
                ta3.setLineWrap(true);
                i=02;
                query1="SELECT *FROM "+g+" where sno='"+i+"';";

                tyr1(query1);

            }} else if(rd81.isSelected()) {
                rd82.setSelected(true);
                if(rd82.isSelected()) {
                    ta3.setWrapStyleWord(true);
                ta3.setLineWrap(true);
                    i=03;
                    query1="SELECT *FROM "+g+" where sno='"+i+"';";

                    tyr1(query1);
                }} else if(rd82.isSelected()){
                    rd83.setSelected(true);
                    if(rd83.isSelected()) {
                        ta3.setWrapStyleWord(true);
                        ta3.setLineWrap(true);

                        i=04;
                        query1="SELECT *FROM "+g+" where sno='"+i+"';";

                        tyr1(query1);
                    }} else if(rd83.isSelected()){
                        rd84.setSelected(true);
                        if(rd84.isSelected()) {
                            ta3.setWrapStyleWord(true);
                            ta3.setLineWrap(true);

                            i=05;
                            query1="SELECT *FROM "+g+" where sno='"+i+"';";

                            tyr1(query1);
                        }} else if(rd84.isSelected()){
                            rd85.setSelected(true);
                            if(rd85.isSelected()) {
                                ta3.setWrapStyleWord(true);
                                ta3.setLineWrap(true);

                                i=06;
                                query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                tyr1(query1);
                            }} else if(rd85.isSelected()){
                                rd86.setSelected(true);
                                if(rd86.isSelected()) {
                                    ta3.setWrapStyleWord(true);
                                    ta3.setLineWrap(true);

                                    i=07;
                                    query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                    tyr1(query1);
                                }} else if(rd86.isSelected()){
                                    rd87.setSelected(true);
                                    if(rd87.isSelected()) {
                                        ta3.setWrapStyleWord(true);
                                        ta3.setLineWrap(true);
                                        i = 8;
                                        query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                        tyr1(query1);
                                    }} else if(rd87.isSelected()){
                                        rd88.setSelected(true);
                                        if(rd88.isSelected()) {
                                            ta3.setWrapStyleWord(true);
                                            ta3.setLineWrap(true);

                                            i=9;
                                            query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                            tyr1(query1);
                                        }}
        else if(rd88.isSelected()){
                                        rd89.setSelected(true);
                                        if(rd89.isSelected()) {
                                            ta3.setWrapStyleWord(true);
                                            ta3.setLineWrap(true);

                                            i=10;
                                            query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                            tyr1(query1);
                                        }}
        }
else if(c==3){
        String query1 =null;
        int i=1;
        if(rd80.isSelected()) {
            rd81.setSelected(true);
            if(rd81.isSelected()) {
                ta3.setWrapStyleWord(true);
                ta3.setLineWrap(true);
                i=02;
                query1="SELECT *FROM "+g+" where sno='"+i+"';";

                tyr2(query1);

            }} else if(rd81.isSelected()) {
                rd82.setSelected(true);
                if(rd82.isSelected()) {
ta3.setWrapStyleWord(true);
                        ta3.setLineWrap(true);
                    i=03;
                    query1="SELECT *FROM "+g+" where sno='"+i+"';";

                    tyr2(query1);
                }} else if(rd82.isSelected()){
                    rd83.setSelected(true);
                    if(rd83.isSelected()) {
                        ta3.setWrapStyleWord(true);
                        ta3.setLineWrap(true);

                        i=04;
                        query1="SELECT *FROM "+g+" where sno='"+i+"';";

                        tyr2(query1);
                    }} else if(rd83.isSelected()){
                        rd84.setSelected(true);
                        if(rd84.isSelected()) {
                            ta3.setWrapStyleWord(true);
                            ta3.setLineWrap(true);

                            i=05;
                            query1="SELECT *FROM "+g+" where sno='"+i+"';";

                            tyr2(query1);
                        }} else if(rd84.isSelected()){
                            rd85.setSelected(true);
                            if(rd85.isSelected()) {
                                ta3.setWrapStyleWord(true);
                                ta3.setLineWrap(true);

                                i=06;
                                query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                tyr2(query1);
                            }} else if(rd85.isSelected()){
                                rd86.setSelected(true);
                                if(rd86.isSelected()) {
                                    ta3.setWrapStyleWord(true);
                                    ta3.setLineWrap(true);

                                    i=07;
                                    query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                    tyr2(query1);
                                }} else if(rd86.isSelected()){
                                    rd87.setSelected(true);
                                    if(rd87.isSelected()) {
                                        ta3.setWrapStyleWord(true);
                                        ta3.setLineWrap(true);

                                        i = 8;
                                        query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                        tyr2(query1);
                                    }} else if(rd87.isSelected()){
                                        rd88.setSelected(true);
                                        if(rd88.isSelected()) {
                                            ta3.setWrapStyleWord(true);
                                            ta3.setLineWrap(true);

                                            i=9;
                                            query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                            tyr2(query1);
                                        }}
        else if(rd88.isSelected()){
                                        rd89.setSelected(true);
                                        if(rd89.isSelected()) {
                                            ta3.setWrapStyleWord(true);
                                            ta3.setLineWrap(true);

                                            i=10;
                                            query1="SELECT *FROM "+g+" where sno='"+i+"';";

                                            tyr2(query1);
                                        }}
    
        }
}
void level(int x){
    gh5.setText(""+x);
    
}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
     if(rd7.isSelected()||rd8.isSelected()||rd9.isSelected()){main_2.setVisible(true);}
    }                                        

    private void main_WindowOpened(java.awt.event.WindowEvent evt) {                                   
        q4= new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                count9++;
                if(count9==60)
                {

                    q4.stop();
                }

                else
                tf88.setText("09:"+count9);

            }
        } );
        q3= new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                count8++;
                if(count8==60)
                {

                    q3.stop();
                    q4.start();
                }

                else
                tf88.setText("08:"+count8);

            }
        } );
        q2= new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                count7++;
                if(count7==60)
                {

                    q2.stop();
                    q3.start();
                }

                else
                tf88.setText("07:"+count7);

            }
        } );
        
        
        
        q1= new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                count6++;
                if(count6==60)
                {

                    q1.stop();
                    q2.start();
                }

                else
                tf88.setText("06:"+count6);

            }
        } );
         
        
        
        q= new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                count5++;
                if(count5==60)
                {

                    q.stop();
                    q1.start();
                }

                else
                tf88.setText("05:"+count5);

            }
        } );
        p= new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                count4++;
                if(count4==60)
                {

                    p.stop();
                    q.start();

                }

                else
                tf88.setText("04:"+count4);

            }
        } );
        op= new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                count3++;
                if(count3==60)
                {

                    op.stop();
                    p.start();

                }

                else
                tf88.setText("03:"+count3);

            }
        } );

        u= new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                count2++;
                if(count2==60)
                {

                    u.stop();
                    op.start();

                }

                else
                tf88.setText("02:"+count2);

            }
        } );
        i= new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                count1++;
                if(count1==60)
                {

                    i.stop();
                    u.start();

                }

                else
                tf88.setText("01:"+count1);

            }
        } );
        t= new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                count++;
                if(count==60)
                {

                    t.stop();
                    i.start();

                }
                else
                tf88.setText("00:"+count);

            }
        } );
        t.start();

            String npa=JOptionPane.showInputDialog(null,"Enter Your User Name");
            Y=npa;
            
            try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/sireesh", "root","root");
            Statement stmt = (Statement) con.createStatement();
            String query="Select level,user_name from iit where user_name='"+npa+"';";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()) {
                String qno = rs.getString("level");
                gh5.setText(qno);
                    x=qno;
                    
                    }
} catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());}
            
            int c=Integer.parseInt(x);
        if(sub.getText().equals("Mathematics")){
        if(c==1){
       String g="SELECT *FROM matha where sno='"+1+"';";
            tyr(g);}
         if(c==2)
        {
            String g="SELECT *FROM mathb where sno='"+1+"';";
            tyr1(g);
        }
         if(c==3)
        {
            String g="SELECT *FROM mathc where sno='"+1+"';";
            tyr2(g);
        }}
         if(sub.getText().equals("Physics")){
            if(c==1){
       String g="SELECT *FROM physicsa where sno='"+1+"';";
            tyr(g);}
         if(c==2)
        {
            String g="SELECT *FROM physicsb where sno='"+1+"';";
            tyr1(g);
        }
         if(c==3)
        {
            String g="SELECT *FROM physicsc where sno='"+1+"';";
            tyr2(g);
        }
            
        }
         if(sub.getText().equals("Chemistry")){
            if(c==1){
       String g="SELECT *FROM chemistrya where sno='"+1+"';";
            tyr(g);}
         if(c==2)
        {
            String g="SELECT *FROM chemistryb where sno='"+1+"';";
            tyr1(g);
        }
         if(c==3)
        {
            String g="SELECT *FROM chemistryc where sno='"+1+"';";
            tyr2(g);
        }
            }
        rd80.setSelected(true);
        JOptionPane.showMessageDialog(null,"maximum time alloted to Question is 30 mins Per subject");
    }                                  

    private void main_WindowActivated(java.awt.event.WindowEvent evt) {                                      

    }                                     

    private void main_FocusGained(java.awt.event.FocusEvent evt) {                                  

    }                                 

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {                                      

    }                                     

    private void tf88ActionPerformed(java.awt.event.ActionEvent evt) {                                     

    }                                    
void main(){
    int c=Integer.parseInt(x);
        if(sub.getText().equals("Mathematics")){
        if(c==1){
       String g="SELECT *FROM matha where sno='"+1+"';";
            tyr(g);}
         if(c==2)
        {
            String g="SELECT *FROM mathb where sno='"+1+"';";
            tyr1(g);
        }
         if(c==3)
        {
            String g="SELECT *FROM mathc where sno='"+1+"';";
            tyr2(g);
        }}
         if(sub.getText().equals("Physics")){
            if(c==1){
       String g="SELECT *FROM physicsa where sno='"+1+"';";
            tyr(g);}
         if(c==2)
        {
            String g="SELECT *FROM physicsb where sno='"+1+"';";
            tyr1(g);
        }
         if(c==3)
        {
            String g="SELECT *FROM physicsc where sno='"+1+"';";
            tyr2(g);
        }
            
        }
         if(sub.getText().equals("Chemistry")){
            if(c==1){
       String g="SELECT *FROM chemistrya where sno='"+1+"';";
            tyr(g);}
         if(c==2)
        {
            String g="SELECT *FROM chemistryb where sno='"+1+"';";
            tyr1(g);
        }
         if(c==3)
        {
            String g="SELECT *FROM chemistryc where sno='"+1+"';";
            tyr2(g);
        }
            }
        rd80.setSelected(true);
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(rd89.isSelected())
        {
           String x=sub.getText();
           if(x.equals("Mathematics"))
           {
               sub.setText("Physics");
               main();
               
           }
           else if(x.equals("Physics"))
           {
               sub.setText("Chemistry");
               main();
           
           }
           else if(x.equals("Chemistry"))
           {
               sub.setText("Mathematics");
               main();
           
           }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Attempt All The Question");
        }

    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
Mains1 h= new Mains1();
h.thanks();
star1 p= new star1();
p.setVisible(true);
this.dispose();
    }                                         

    private void bb3ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        int c=Integer.parseInt(x);

        if(sub.getText().equals("Mathematics")){
            if(c==1){
                math(c,"matha");
            }
            if(c==2)
            {
                math(c,"mathb");
            }
            if(c==3)
            {
                math(c,"mathc");
            }}
            else if(sub.getText().equals("Physics")){
                if(c==1){
                    math(c,"physicsa");
                }
                if(c==2)
                {
                    math(c,"physicsb");
                }
                if(c==3)
                {
                    math(c,"physicsc");
                }}
                else if(sub.getText().equals("Chemistry")){
                    if(c==1){
                        math(c,"chemistrya");
                    }
                    if(c==2)
                    {
                        math(c,"chemistryb");
                    }
                    if(c==3)
                    {
                        math(c,"chemistryc");
                    }}
    }                                   

    private void bb3FocusGained(java.awt.event.FocusEvent evt) {                                

    }                               

    private void rd48ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String x=lk5.getText();
        String y="d";
        if(y.equals(x))
        {
            int o=Integer.parseInt(hk5.getText());
            int h=o+1;
            hk5.setText(""+h);
        }
    }                                    

    private void rd47ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String x=lk5.getText();
        String y="c";
        if(y.equals(x))
        {
            int o=Integer.parseInt(hk5.getText());
            int h=o+1;
            hk5.setText(""+h);
        }
    }                                    

    private void rd46ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String x=lk5.getText();
        String y="b";
        if(y.equals(x))
        {
            int o=Integer.parseInt(hk5.getText());
            int h=o+1;
            hk5.setText(""+h);
        }
    }                                    

    private void rd45ActionPerformed(java.awt.event.ActionEvent evt) {                                     

        String x=lk5.getText();
        String y="a";
        if(y.equals(x))
        {
            int o=Integer.parseInt(hk5.getText());
            int h=o+1;
            hk5.setText(""+h);
        }
    }                                    

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(rd89.isSelected())
        {
         int x=Integer.parseInt(hk5.getText());
         
         
        Mains1 j= new Mains1();
        
       String g= tf88.getText();
       j.stats(x,g);
         
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Attempt All The Question");
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton b1;
    private javax.swing.JButton bb5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel dsub;
    private javax.swing.JLabel gh5;
    private javax.swing.JLabel hk5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb20;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel level;
    private javax.swing.JLabel lk5;
    private javax.swing.JDialog main_2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel pd1;
    private javax.swing.JLabel pt1;
    private javax.swing.JRadioButton rd53;
    private javax.swing.JRadioButton rd54;
    private javax.swing.JRadioButton rd55;
    private javax.swing.JRadioButton rd56;
    private javax.swing.JRadioButton rd7;
    private javax.swing.JRadioButton rd8;
    private javax.swing.JRadioButton rd80;
    private javax.swing.JRadioButton rd81;
    private javax.swing.JRadioButton rd82;
    private javax.swing.JRadioButton rd83;
    private javax.swing.JRadioButton rd84;
    private javax.swing.JRadioButton rd85;
    private javax.swing.JRadioButton rd86;
    private javax.swing.JRadioButton rd87;
    private javax.swing.JRadioButton rd88;
    private javax.swing.JRadioButton rd89;
    private javax.swing.JRadioButton rd9;
    private javax.swing.JLabel sub;
    private javax.swing.JTextArea ta3;
    private javax.swing.JTextField tf57;
    private javax.swing.JTextField tf88;
    private javax.swing.JLabel tg5;
    private javax.swing.JLabel tt5;
    private javax.swing.JLabel yh5;
    // End of variables declaration                   
}
