/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mindcracker;


import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;


/**
 *
 * @author Student
 */
public class load extends javax.swing.JFrame {

    /**
     * Creates new form load
     */
    private Timer t;
    private int count =0;
    public load() {
        this.setUndecorated(true);
       Toolkit toolkit=Toolkit.getDefaultToolkit();
       double width=toolkit.getScreenSize().getWidth();
       double height=toolkit.getScreenSize().getHeight();
       this.setSize((int)width,(int)height);
        
      initComponents();
      
      
      
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/image_1152682.gif"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 650, 90, 70));

        lb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/ic.v1 (2).png"))); // NOI18N
        getContentPane().add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 310, 310));

        lb1.setBackground(new java.awt.Color(6, 114, 76));
        lb1.setOpaque(true);
        getContentPane().add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2050, 1180));

        lb5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lb5FocusGained(evt);
            }
        });
        lb5.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lb5InputMethodTextChanged(evt);
            }
        });
        getContentPane().add(lb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 80, 30));

        pack();
    }// </editor-fold>                        

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
  t= new Timer(1000, new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent ae) {
          count++;
          if(count==5){
              t.stop(); 
         load d= new load();
         d.dispose();
              welcome1 g= new welcome1();
                   g.setVisible(true);
          }
        lb5.setText(count+"");
      }
  } );
  t.start();
  
    }                                 

    private void lb5FocusGained(java.awt.event.FocusEvent evt) {                                
       
    }                               

    private void lb5InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                           
       
    }                                          

    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
     
               
    }                                    

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
       
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new load().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb5;
    // End of variables declaration                   
}
