/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mindcracker;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class star1 extends javax.swing.JFrame {

    /**
     * Creates new form star1
     */
    public star1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/rsz_1smallgoldstar.jpg"))); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 30));

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/rsz_1smallgoldstar.jpg"))); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 40, 30));

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/rsz_1smallgoldstar.jpg"))); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 40, 30));

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/rsz_1smallgoldstar.jpg"))); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 40, 30));

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mindcracker/rsz_1smallgoldstar.jpg"))); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 270, 60));

        jLabel59.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel59.setText("Rate App !!!!");
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 140, 30));

        jButton1.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jButton1.setText("Done");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 90, 40));

        jLabel1.setBackground(new java.awt.Color(43, 157, 101));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 160));

        lb2.setText("0");
        getContentPane().add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
      
            b1.setBackground(Color.green);
        
            int x=1;
            int d=Integer.parseInt(lb2.getText());
            int y=x+d;
            lb2.setText(""+y);
        
            
        
    }                                  

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
         b2.setBackground(Color.green);
             
              
        int x=1;
            int d=Integer.parseInt(lb2.getText());
            int y=x+d;
            lb2.setText(""+y);
             
        
    }                                  

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        b3.setBackground(Color.green);
             
             
        int x=1;
            int d=Integer.parseInt(lb2.getText());
            int y=x+d;
            lb2.setText(""+y);
             
    }                                  

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
         b4.setBackground(Color.green);
            
              
        int x=1;
            int d=Integer.parseInt(lb2.getText());
            int y=x+d;
            lb2.setText(""+y);
             
    }                                  

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        b5.setBackground(Color.green);
             
             
        int x=1;
            int d=Integer.parseInt(lb2.getText());
            int y=x+d;
            lb2.setText(""+y);
             
    }                                  

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int g=Integer.parseInt(lb2.getText());
        Mains1 d= new Mains1();
        if(g==1||g==2||g==3||g==4||g==5){
            int y=JOptionPane.showConfirmDialog(null," DID YOU like This Application");
            if(y==0){
            JOptionPane.showMessageDialog(null,"Thank you for your Remark");
            d.thanks();
            System.exit(0);
            }
            else if(y==1){
        String x=JOptionPane.showInputDialog(" Reason(Any Improvement Needed)");
        JOptionPane.showMessageDialog(null,"Thank you for your Remark");
        this.dispose();
        d.thanks();
        System.exit(0);
        }
        
     }
      
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(star1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(star1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(star1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(star1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new star1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb2;
    // End of variables declaration                   
}
